// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvuxvltqjvzcupofecgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2dXh2bHRxanZ6Y3Vwb2ZlY2d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMTgwMTIsImV4cCI6MjA3MDY5NDAxMn0.3aLqWFjon45L6nS0pq1ZUtZBRLIxmsXgczxcHC07BA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});